/camera_front:
    camera_i_mx_id: 1944301001CE7F1300
    camera_i_ip: '192.168.111.31'
    rgb_i_fps: 30.0
    rgb_i_publish_topic: true
    rgb_i_height: 1080
    rgb_i_width: 1920
    rgb_i_preview_size: 416
    rgb_i_resolution: '720'
    camera_i_nn_type: none
    camera_i_pipeline_type: RGB
    
/camera_rear:
    camera_i_mx_id: 1944301091F7761300
    camera_i_ip: '192.168.111.32'
    rgb_i_fps: 30.0
    rgb_i_publish_topic: true
    rgb_i_height: 1080
    rgb_i_width: 1920
    rgb_i_preview_size: 416
    rgb_i_resolution: '1080'
    camera_i_nn_type: none
    camera_i_pipeline_type: RGB
